using ProgramacionFuncionalCSharp.Lambdas;
using ProgramacionFuncionalCSharp.DelegateOrCallBacks;
using ProgramacionFuncionalCSharp.CursoCSharp;
using ProgramacionFuncionalCSharp.LINQ;
using ProgramacionFuncionalCSharp.String;
using ProgramacionFuncionalCSharp.Object;
using ProgramacionFuncionalCSharp.Integer;


// Console.WriteLine("\nstart lambdas!");
// const int numberOne = 10, numberTwo = 20;
// Console.WriteLine($"¿el número es par?: {Lambda.isPar(numberOne)}");
// Console.WriteLine($"¿el correo es válido?: {Lambda.IsValidEmail("alexanderardilagmail.com")}");
// Console.WriteLine($"el resultado de la suma es: {Lambda.sum(numberOne, numberTwo)}");
// Console.WriteLine($"validador: {Lambda.CompanyEmail("alexanderardila@HOTMAIL.com")}");
// Console.WriteLine("saludar: ");
// Lambda.greet("Hola como estas");
// Lambda.greetMultipleTimes("Hola varias veces", 4);
// Console.WriteLine("end lambdas! \n");

// Console.WriteLine("\nstart delegados!");
// Delegado.CallbackDelegate retiro = Delegado.Retiro;
// Delegado.CallbackDelegate deposito = Delegado.Deposito;
// Delegado.EjecutarOperacion(retiro, 20, 200);
// Delegado.EjecutarOperacion(deposito, 40, 260);
// //creamos un lambda para un deposito con intereses del 2% si cantidad es mayor a 200
// Delegado.CallbackDelegate depositoInteres = (cantidad, monto) => cantidad > 200 ? cantidad + monto + (cantidad * 0.02f) : cantidad + monto;
// Delegado.EjecutarOperacion(depositoInteres, 202, 500);
// Console.WriteLine("end delegados! \n");

// Console.WriteLine("\nstart LINQ!");
// Console.WriteLine("Filtrado y busqueda de elementos");
// LinqMethods.Where();
// LinqMethods.WhereWithLet();
// LinqMethods.OfType();
// LinqMethods.Find();
// LinqMethods.Single();
// LinqMethods.SingleOrDefault();
// LinqMethods.First();
// LinqMethods.FirstOrDefault();
// LinqMethods.Last();
// LinqMethods.LastOrDefault();
// LinqMethods.ElementAt();
// LinqMethods.ElementAtOrDefault();
// LinqMethods.DefaultIfEmpty();
// Console.WriteLine("Proyección");
// LinqMethods.Select();
// LinqMethods.SelectMany();
// Console.WriteLine("Ordenamiento");
// LinqMethods.OrderBy();
// LinqMethods.OrderByDescending();
// LinqMethods.ThenBy();
// LinqMethods.ThenByDescending();
// LinqMethods.Reverse();
// Console.WriteLine("Agrupación");
// LinqMethods.GroupBy();
// Console.WriteLine("Conjuntos");
// LinqMethods.Join();
// LinqMethods.GroupJoin();
// LinqMethods.LeftJoin();
// LinqMethods.Contains();
// LinqMethods.Distinct();
// LinqMethods.DistinctBy();
// LinqMethods.Any();
// LinqMethods.All();
// LinqMethods.Union();
// LinqMethods.UnionBy();
// LinqMethods.Concat();
// LinqMethods.Except();
// LinqMethods.Intersect();
// LinqMethods.IntersectBy();
// LinqMethods.SequenceEqual();
// LinqMethods.Zip();
// Console.WriteLine("Paginación");
// LinqMethods.Take();
// LinqMethods.Skip();
// LinqMethods.TakeWhile();
// LinqMethods.SkipWhile();
// LinqMethods.TakeLast();
// LinqMethods.SkipLast();
// LinqMethods.Range();
// Console.WriteLine("Agregación y reducción");
// LinqMethods.Aggregate();
// LinqMethods.Count();
// LinqMethods.Average();
// LinqMethods.Max();
// LinqMethods.Min();
// LinqMethods.Sum();
// LinqMethods.MaxBy();
// LinqMethods.MinBy();
// Console.WriteLine("Conversión");
// LinqMethods.ToList();
// LinqMethods.ToLookUp();
// LinqMethods.ToArray();
// LinqMethods.ToDictionary();
// LinqMethods.ToHashSet();
// LinqMethods.Cast();
// LinqMethods.AsEnumerable();
// Console.WriteLine("end LINQ! \n");

// Console.WriteLine("\nstart Tuplas!");
// Tuplas.MethodTuplas();
// Console.WriteLine("end Tuplas! \n");

// Console.WriteLine("\nstart object methods!");
// ObjectMethods.Equals();
// ObjectMethods.MethodGetHashCode();
// ObjectMethods.ToString_();
// ObjectMethods.GetType_();
// ObjectMethods.ReferenceEquals();
// Console.WriteLine("end Queries! \n");

// Console.WriteLine("\nstart string methods!");
// StringMethods.StartsWith();
// StringMethods.EndsWith();
// StringMethods.IsNullOrEmpty();
// StringMethods.Compare();
// StringMethods.Concat();
// StringMethods.Contains();
// StringMethods.Format();
// StringMethods.Join();
// StringMethods.Replace();
// StringMethods.Substring();
// StringMethods.Trim();
// StringMethods.TrimEnd();
// StringMethods.TrimStart();
// StringMethods.ToLower();
// StringMethods.ToUpper();
// Console.WriteLine("end Queries! \n");

// Console.WriteLine("\nstart integer methods!");
// IntegerMethods.TryParse();
// IntegerMethods.Parse();
// IntegerMethods.CompareTo();
// Console.WriteLine("end Queries! \n");